<?php
// $Id: beautytips_advanced.module,v 1.1 2010/01/24 15:17:15 rsvelko Exp $
/**
 * @file
 * BeautyTips Advanced ( beautytips_advanced ) is a UI enhancement for the BeautyTips module.
 *
 **/


/**
 * Implementation of hook_init().
 */

function beautytips_advanced_init() {
  beautytips_advanced_define_btip("bt_drupal_login_block", "hulu");
}


/**
 * Prototype function that uses the btip api
 */

function beautytips_advanced_define_btip($btip_name, $btip_type) {

  if ($btip_type == "hulu") {
    // add beautytips jquery popups to the login/register/logout block (class="login-block") using the beautytips module's API  
    $options[$btip_name] = array(
      'area' => '.login-block a',
    //    'ajaxPath' => array(0 => "$(this).attr('href')"),
      'text' => '<b>BeautyTips</b><hr />This is a tooltip.',
      'trigger' => array(0 => 'mouseover'),
      'positions' => array('right', 'left'),
      'fill' => '#F4F4F4',
      'strokeStyle' => '#666666', 
      'spikeLength' => 20,
      'spikeGirth' => 10,
      'width' => 350,
      'overlap' => 0,
      'centerPointY' => 1,
      'cornerRadius' => 0,
      'cssStyles' => array(
        'fontFamily' => '"Lucida Grande",Helvetica,Arial,Verdana,sans-serif', 
        'fontSize' => '12px',
        'padding' => '10px 14px'
      ),
      'shadow' => true,
      'shadowColor' => 'rgba(0,0,0,.5)',
      'shadowBlur' => 8,
      'shadowOffsetX' => 4,
      'shadowOffsetY' => 4,

    'hoverIntentOpts' => array(
      'interval' => 100,
      'timeout' => 500,
    ),
      
    );

    beautytips_add_beautytips($options);
  
  }

}

/**
 * Implementation of hook_menu().
 */
function beautytips_advanced_menu() {
  $items = array();
  $items['admin/settings/beautytips_advanced'] = array(
    'title' => 'BeautyTips Advanced',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('beautytips_advanced_admin'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 *  Beautytips Advanced administration page
 */
function beautytips_advanced_admin() {

/*   $form['beautytips_advanced_textarea'] = array(
    '#type' => 'textfield',
    '#title' => 'Enter the form id(s) to use for text popup beautytips',
    '#description' => t('You need to use Drupal php syntax like page_node_form'),
    '#default_value' => variable_get('beautytips_form_id', ''),
  );
 */  
//  $path = drupal_get_path('module', 'beautytips') .'/js/bt_admin_page.js';
// drupal_add_js($path);
//  beautytips_add_beautytips();

//  return system_settings_form($form);
  return "This page will contain the btips manager.";
}



